// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBYxokvedBRkidYMs07yqfl_Eye-naYk',
    appId: '1:640117673086:web:2cbbb9f18435d642b45c2f',
    messagingSenderId: '640117673086',
    projectId: 'servicex-dea01',
    authDomain: 'servicex-dea01.firebaseapp.com',
    storageBucket: 'servicex-dea01.firebasestorage.app',
    measurementId: 'G-BQ68C27P14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpMaeHPuJdkGWILQ6RLqEbVBiz66iHBXo',
    appId: '1:640117673086:android:e4e67103d43607bcb45c2f',
    messagingSenderId: '640117673086',
    projectId: 'servicex-dea01',
    storageBucket: 'servicex-dea01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB77CMvkrBv4436GitwdhiglrDFCObuAGE',
    appId: '1:640117673086:ios:0df3e6c8493657e8b45c2f',
    messagingSenderId: '640117673086',
    projectId: 'servicex-dea01',
    storageBucket: 'servicex-dea01.firebasestorage.app',
    iosBundleId: 'com.example.servicexClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB77CMvkrBv4436GitwdhiglrDFCObuAGE',
    appId: '1:640117673086:ios:0df3e6c8493657e8b45c2f',
    messagingSenderId: '640117673086',
    projectId: 'servicex-dea01',
    storageBucket: 'servicex-dea01.firebasestorage.app',
    iosBundleId: 'com.example.servicexClientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRBYxokvedBRkidYMs07yqfl_Eye-naYk',
    appId: '1:640117673086:web:d9a3a6beaea1edddb45c2f',
    messagingSenderId: '640117673086',
    projectId: 'servicex-dea01',
    authDomain: 'servicex-dea01.firebaseapp.com',
    storageBucket: 'servicex-dea01.firebasestorage.app',
    measurementId: 'G-K48BVWQLB8',
  );
}
