// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRudqWggDktMkbdJzQ34QM3MTKLC9BN2A',
    appId: '1:416229849888:web:156318f0125eb015bb3545',
    messagingSenderId: '416229849888',
    projectId: 'servicex-220b5',
    authDomain: 'servicex-220b5.firebaseapp.com',
    storageBucket: 'servicex-220b5.firebasestorage.app',
    measurementId: 'G-RW6Y5Q5D3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd2D66pBj3t8aGxHVlscX15VPh8--jFAE',
    appId: '1:416229849888:android:bf4915cd0f39bf1bbb3545',
    messagingSenderId: '416229849888',
    projectId: 'servicex-220b5',
    storageBucket: 'servicex-220b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLsv2MKci7N9vh818hDQUxp2oY-KmgPM',
    appId: '1:416229849888:ios:a189e5c0de12ded2bb3545',
    messagingSenderId: '416229849888',
    projectId: 'servicex-220b5',
    storageBucket: 'servicex-220b5.firebasestorage.app',
    iosBundleId: 'com.example.servicexClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaLsv2MKci7N9vh818hDQUxp2oY-KmgPM',
    appId: '1:416229849888:ios:a189e5c0de12ded2bb3545',
    messagingSenderId: '416229849888',
    projectId: 'servicex-220b5',
    storageBucket: 'servicex-220b5.firebasestorage.app',
    iosBundleId: 'com.example.servicexClientApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRudqWggDktMkbdJzQ34QM3MTKLC9BN2A',
    appId: '1:416229849888:web:594ea45f73ed559bbb3545',
    messagingSenderId: '416229849888',
    projectId: 'servicex-220b5',
    authDomain: 'servicex-220b5.firebaseapp.com',
    storageBucket: 'servicex-220b5.firebasestorage.app',
    measurementId: 'G-SNVS34G17B',
  );
}
